# Generated by Django 3.1 on 2021-04-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210429_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_tutoring',
        ),
        migrations.RemoveField(
            model_name='post',
            name='looking_for',
        ),
        migrations.RemoveField(
            model_name='post',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='min_price',
        ),
    ]
